
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '16'
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run dist
after_script:
  - npminstall codecov && codecov
